replicaCount: 1

image:
  registry: docker.io
  repository: mahdidarabi/openssh-server
  tag: "0.0.1"
  pullPolicy: IfNotPresent

#https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 22
  nodePort: ""

resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 2Gi
    cpu: 1000m

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
