apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: ssh-pod
    meta.helm.sh/release-namespace: ssh-pod
  labels:
    app.kubernetes.io/instance: ssh-pod
    app.kubernetes.io/name: ssh-pod
    app.kubernetes.io/version: 0.0.1
  name: ssh-pod
  namespace: ssh-pod
spec:
  ports:
    - name: http
      port: 22
      protocol: TCP
      targetPort: http
  selector:
    app: ssh-pod
  type: ClusterIP
