apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-pod.fullname" . }}
  labels:
    {{- include "ssh-pod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "ssh-pod.name" . }}
